name: Update Rakahomelab Status Screenshot

on:
  schedule:
    - cron: '0 * * * *' # Mlaku otomatis saben 1 jam
  workflow_dispatch:     # Tombol manual "Run" neng tab Actions

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:         # Iki WAJIB ON ben isoh nge-push
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Take Screenshot
        uses: microlinkhq/screenshot-action@v1.1.0
        with:
          # URL mbok ganti 'uptime' (ra nganggo kuma) mergo neng browser-mu rutené kuwi, bolo!
          url: https://uptimekuma.rakahomelab.my.id/status/server 
          width: 1280
          height: 720
          type: png
          overlay: false
          filename: status_screenshot.png

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update server status heartbeat screenshot 📸"
          file_pattern: 'status_screenshot.png'
