name: Update Rakahomelab Status Screenshot

on:
  schedule:
    - cron: '0 * * * *' # Mlaku otomatis saben 1 jam
  workflow_dispatch:     # Tombol manual "Run" neng tab Actions

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install shot-scraper
        run: |
          pip install shot-scraper
          shot-scraper install

      - name: Take Screenshot
        run: |
          # URL mbok ganti 'uptimekuma' sesuai screenshot browser-mu yo!
          shot-scraper https://uptimekuma.rakahomelab.my.id/status/server \
            -o status_screenshot.png \
            --width 1280 --height 720 --wait 5000

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update server status heartbeat screenshot 📸"
          file_pattern: 'status_screenshot.png'
